version: '3'
services: 
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: MssqlPassword1
    volumes:
      - mssql-data:/var/opt/mssql/data
    networks:
      - mssql-network
    ports:
      - 1433:1433
    restart: unless-stopped
    


volumes: 
  mssql-data:

networks: 
  mssql-network:
    driver: bridge