version: '3'
services: 
  postgres:
    image: postgres:alpine
    ports: 
      - 5432:5432
    volumes: 
      - postgres-data:/data/postgres
    environment: 
      POSTGRES_USER: uni
      POSTGRES_PASSWORD: uni
      PGDATA: /data/postgres
    restart: unless-stopped
    networks: 
      - postgres-network
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@hs-bochum.de
      PGADMIN_DEFAULT_PASSWORD: uni
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 80:80
    restart: unless-stopped
    networks: 
      - postgres-network

volumes: 
  postgres-data:
  pgadmin-data:

networks: 
  postgres-network:
    driver: bridge